# Use root/example as user/password credentials
version: '3.9'

services:
  auth-api:
    build: .
    ports:
      - 80:3000
    restart: unless-stopped
    environment: 
      PORT:         3000
      MONGO_URI:    ${MONGO_URI:?MONGO_URI is missing}
      MONGO_DB:     ${MONGO_DB:?MONGO_DB is missing}
      RABBITMQ_URL: ${RABBITMQ_URL:?RABBITMQ_URL is missing}
      JWT_SECRET:   ${JWT_SECRET:?JWT_SECRET is missing}

