# Use root/example as user/password credentials
version: '3.9'

services:
  auth-api:
    build: .
    ports:
      - 80:3000
    depends_on:
      - auth-db
    restart: unless-stopped
    environment: 
      PORT:         3000
      MONGO_URI:    mongodb://root:example@auth-db:27017
      MONGO_DB:     db
      RABBITMQ_URL: ${RABBITMQ_URL:?RABBITMQ_URL is missing}
      JWT_SECRET:   ${JWT_SECRET:?JWT_SECRET is missing}

  auth-db:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_ROOT_DATABASE: db
